# Generated by Django 4.2.7 on 2023-12-25 22:30

import blog.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_alter_post_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="image",
            field=models.ImageField(
                blank=True,
                max_length=550,
                null=True,
                upload_to=blog.utils.upload_location,
            ),
        ),
    ]
