# Generated by Django 4.2.7 on 2023-12-25 22:34

import blog.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_alter_post_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to=blog.utils.upload_location
            ),
        ),
    ]
